[package]
name = "race_sdk"
version = "0.1.0"
edition = "2024"

[dependencies]

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Foundation", "Win32_System", "Win32_System_Memory"] }
